name: blockchain_notarization
channels:
  - conda-forge

dependencies:
  - pandas
  - pip


  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz


  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - otree
    - web3